CREATE TABLE designations (
	id INT(12) NOT NULL AUTO_INCREMENT,
	designation VARCHAR(100) NULL DEFAULT NULL,
	created VARCHAR(255) NULL DEFAULT NULL,
	modified VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY(id),
	UNIQUE idx_unq_designation(designation)
);

ALTER TABLE designations ADD COLUMN `sss` VARCHAR(255) NULL DEFAULT NULL AFTER designation;
ALTER TABLE designations ADD COLUMN `pag_ibig` VARCHAR(255) NULL DEFAULT NULL AFTER sss;
ALTER TABLE designations ADD COLUMN `phil_health` VARCHAR(255) NULL DEFAULT NULL AFTER pag_ibig;